#!/bin/sh
set -e
set -u

cat > ci/vars <<EOF
BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
export VERSION=\${BRANCH}
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF

. ci/vars
docker-compose build
